"""Shell completion generators.

The word lists are read from the real option specs and the real ``themes/``
directory, so ``sentinel completion --write`` can never emit a stale list.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from . import options as O
from . import themes

COMPLETIONS_DIR = O.REPO_ROOT / "completions"

COMMANDS = (
    "customize", "tui", "preview", "theme", "themes", "toggle", "set", "get",
    "apply", "reload", "doctor", "install", "uninstall", "completion",
)


def _value_choices() -> Dict[str, List[str]]:
    """Setting key -> completable values (empty when the domain is numeric/free)."""
    return {spec.key: spec.choices() for spec in O.SPECS}


def render_bash() -> str:
    choices = _value_choices()
    keys_with_values = [k for k, v in choices.items() if v]
    case_arms = "\n".join(
        f"        {key}) COMPREPLY=($(compgen -W \"{' '.join(choices[key])}\" -- \"$cur\")); return ;;"
        for key in keys_with_values
    )
    return f"""# bash completion for tmux-sentinel
# Generated by `sentinel completion --write`. Do not edit by hand.

_sentinel() {{
    local cur prev cmd
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    cmd="${{COMP_WORDS[1]}}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=($(compgen -W "{' '.join(COMMANDS)} --version --help" -- "$cur"))
        return
    fi

    case "$cmd" in
    theme|themes)
        COMPREPLY=($(compgen -W "{' '.join(themes.list_themes())}" -- "$cur"))
        ;;
    toggle)
        COMPREPLY=($(compgen -W "{' '.join(O.SEGMENTS)}" -- "$cur"))
        ;;
    get)
        COMPREPLY=($(compgen -W "{' '.join(O.KEYS)} --verbose" -- "$cur"))
        ;;
    set)
        if [ "$COMP_CWORD" -eq 2 ]; then
            COMPREPLY=($(compgen -W "{' '.join(O.KEYS)}" -- "$cur"))
            return
        fi
        case "$prev" in
{case_arms}
        esac
        ;;
    preview)
        case "$prev" in
        --theme|-t) COMPREPLY=($(compgen -W "{' '.join(themes.list_themes())}" -- "$cur")); return ;;
        --glyphs|-g) COMPREPLY=($(compgen -W "{' '.join(O.GLYPH_MODES)}" -- "$cur")); return ;;
        --sim) COMPREPLY=($(compgen -W "healthy alert both" -- "$cur")); return ;;
        esac
        COMPREPLY=($(compgen -W "--theme --glyphs --session --width --sim" -- "$cur"))
        ;;
    doctor)
        COMPREPLY=($(compgen -W "--fix" -- "$cur"))
        ;;
    install)
        COMPREPLY=($(compgen -W "--dry-run" -- "$cur"))
        ;;
    uninstall)
        COMPREPLY=($(compgen -W "--dry-run --keep-options --purge" -- "$cur"))
        ;;
    completion)
        COMPREPLY=($(compgen -W "bash zsh --write" -- "$cur"))
        ;;
    esac
}}
complete -F _sentinel sentinel
"""


def render_zsh() -> str:
    choices = _value_choices()
    theme_list = " ".join(themes.list_themes())
    key_arms = "\n".join(
        f"            {key}) _values '{key}' {' '.join(choices[key])} ;;"
        for key, values in choices.items() if values
    )
    return f"""#compdef sentinel
# zsh completion for tmux-sentinel
# Generated by `sentinel completion --write`. Do not edit by hand.

_sentinel() {{
    local -a commands
    commands=(
        'customize:interactive curses customizer'
        'preview:render the real bar in this terminal'
        'theme:list or set the theme'
        'toggle:enable/disable one segment'
        'set:set one setting'
        'get:print settings'
        'apply:regenerate artifacts and reload tmux'
        'doctor:diagnose the installation'
        'install:source sentinel.conf from your tmux config'
        'uninstall:remove sentinel from your tmux config'
        'completion:emit shell completions'
    )

    if (( CURRENT == 2 )); then
        _describe -t commands 'sentinel command' commands
        return
    fi

    case "${{words[2]}}" in
    theme|themes)
        _values 'theme' {theme_list}
        ;;
    toggle)
        _values 'segment' {' '.join(O.SEGMENTS)}
        ;;
    get)
        _values 'setting' {' '.join(O.KEYS)}
        ;;
    set)
        if (( CURRENT == 3 )); then
            _values 'setting' {' '.join(O.KEYS)}
            return
        fi
        case "${{words[3]}}" in
{key_arms}
        esac
        ;;
    preview)
        _arguments \\
            '--theme[preview a theme]:theme:({theme_list})' \\
            '--glyphs[preview a glyph set]:glyphs:({' '.join(O.GLYPH_MODES)})' \\
            '--session[simulated session name]:name:' \\
            '--width[bar width]:columns:' \\
            '--sim[simulated state]:state:(healthy alert both)'
        ;;
    doctor)
        _arguments '--fix[regenerate and relink first]'
        ;;
    install)
        _arguments '--dry-run[print the change without making it]'
        ;;
    uninstall)
        _arguments \\
            '--dry-run[print the changes without making them]' \\
            '--keep-options[keep options.conf without asking]' \\
            '--purge[also delete options.conf]'
        ;;
    completion)
        _values 'shell' bash zsh
        ;;
    esac
}}

_sentinel "$@"
"""


def render_completion(shell: str) -> str:
    if shell == "zsh":
        return render_zsh().rstrip("\n")
    return render_bash().rstrip("\n")


def write_completions() -> List[Path]:
    COMPLETIONS_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in (("sentinel.bash", render_bash()), ("_sentinel", render_zsh())):
        path = COMPLETIONS_DIR / name
        O._atomic_write(path, text)
        written.append(path)
    return written
