"""Config and script generator for tmux-sentinel."""

import os
from pathlib import Path
from typing import Dict, Any

from .config import CONFIG_DIR, ENV_FILE, TMUX_CONF_FILE
from .themes import THEMES, GLYPH_SETS


def get_repo_dir() -> Path:
    """Return the base directory of the repository/package."""
    # If installed via git clone or TPM
    return Path(__file__).resolve().parent.parent


def generate_all(cfg: Dict[str, Any]) -> None:
    """Generate both sentinel.conf and env.sh."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    generate_tmux_conf(cfg)
    generate_env_sh(cfg)


def generate_env_sh(cfg: Dict[str, Any]) -> None:
    """Generate the fast POSIX shell environment file for status-right.sh."""
    theme_name = cfg.get("theme", "catppuccin-mocha")
    theme = THEMES.get(theme_name, THEMES["catppuccin-mocha"])

    glyph_mode = cfg.get("glyph_mode", "nerd")
    glyphs = GLYPH_SETS.get(glyph_mode, GLYPH_SETS["nerd"])

    segments = cfg.get("segments", {})
    thresholds = cfg.get("thresholds", {})
    repo_dir = get_repo_dir()
    bin_dir = repo_dir / "bin"

    lines = [
        "#!/bin/sh",
        "# Auto-generated by tmux-sentinel CLI. Do not edit directly.",
        "",
        f'export SENTINEL_THEME="{theme_name}"',
        f'export SENTINEL_DIM="#[fg={theme["dim"]}]"',
        f'export SENTINEL_VAL="#[fg={theme["val"]}]"',
        f'export SENTINEL_SEP="#[fg={theme["sep"]}]{glyphs["sep"]}"',
        f'export SENTINEL_RED="#[fg={theme["alert"]}]"',
        f'export SENTINEL_YEL="#[fg={theme["warn"]}]"',
        f'export SENTINEL_PCH="#[fg={theme["peach"]}]"',
        f'export SENTINEL_INFO="#[fg={theme["info"]}]"',
        "",
        f'export SENTINEL_GLYPH_THERMAL="{glyphs["thermal"]}"',
        f'export SENTINEL_GLYPH_SLEEP="{glyphs["sleep"]}"',
        f'export SENTINEL_GLYPH_DISK="{glyphs["disk"]}"',
        f'export SENTINEL_GLYPH_BATT_FULL="{glyphs["battery_full"]}"',
        f'export SENTINEL_GLYPH_BATT_MID="{glyphs["battery_mid"]}"',
        f'export SENTINEL_GLYPH_BATT_LOW="{glyphs["battery_low"]}"',
        f'export SENTINEL_GLYPH_CPU="{glyphs["cpu"]}"',
        f'export SENTINEL_GLYPH_MEM="{glyphs["memory"]}"',
        f'export SENTINEL_GLYPH_CLIENTS="{glyphs["clients"]}"',
        "",
        f'export SENTINEL_ALERTS_ONLY={"1" if cfg.get("alerts_only", True) else "0"}',
        f'export SENTINEL_SEG_THERMAL={"1" if segments.get("thermal", True) else "0"}',
        f'export SENTINEL_SEG_SLEEP_RISK={"1" if segments.get("sleep_risk", True) else "0"}',
        f'export SENTINEL_SEG_DISK={"1" if segments.get("disk", True) else "0"}',
        f'export SENTINEL_SEG_BATTERY={"1" if segments.get("battery", True) else "0"}',
        f'export SENTINEL_SEG_CPU={"1" if segments.get("cpu", True) else "0"}',
        f'export SENTINEL_SEG_MEMORY={"1" if segments.get("memory", True) else "0"}',
        "",
        f'export SENTINEL_DISK_WARN="{thresholds.get("disk_warn_gb", 25)}"',
        f'export SENTINEL_DISK_CRIT="{thresholds.get("disk_crit_gb", 15)}"',
        f'export SENTINEL_CPU_WARN="{thresholds.get("cpu_warn_pct", 70)}"',
        f'export SENTINEL_CPU_CRIT="{thresholds.get("cpu_crit_pct", 90)}"',
        f'export SENTINEL_BATT_WARN="{thresholds.get("battery_warn_pct", 50)}"',
        f'export SENTINEL_BATT_CRIT="{thresholds.get("battery_crit_pct", 20)}"',
        "",
        f'export SENTINEL_BIN_DIR="{bin_dir}"',
        "",
    ]

    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def generate_tmux_conf(cfg: Dict[str, Any]) -> None:
    """Generate the static tmux configuration sourced by tmux."""
    theme_name = cfg.get("theme", "catppuccin-mocha")
    theme = THEMES.get(theme_name, THEMES["catppuccin-mocha"])

    glyph_mode = cfg.get("glyph_mode", "nerd")
    glyphs = GLYPH_SETS.get(glyph_mode, GLYPH_SETS["nerd"])

    pos = cfg.get("position", "top")
    interval = cfg.get("interval", 10)
    left_cfg = cfg.get("left", {})
    windows_cfg = cfg.get("windows", {})
    segments = cfg.get("segments", {})
    clock_fmt = cfg.get("clock_format", "%H:%M")

    repo_dir = get_repo_dir()
    status_right_script = repo_dir / "scripts" / "status-right.sh"

    accent_symbol = left_cfg.get("accent_symbol", glyphs["accent"])
    max_len = left_cfg.get("max_session_length", 18)

    # Left status bar
    # Mode indicator: normal = accent, prefix = prefix color, copy-mode = copy_mode color
    status_left = (
        f'#[fg=#{{?client_prefix,{theme["prefix"]},#{{?pane_in_mode,{theme["copy_mode"]},{theme["accent"]}}}}}]{accent_symbol}'
        f'#[fg={theme["fg"]},bold] #{{=/{max_len}/…:session_name}} #[default]'
    )

    # Right status bar elements
    # Script output + multi-client indicator + clock
    multi_client_part = ""
    if segments.get("multi_client", True):
        multi_client_part = f'#{{?#{{e|>:#{{session_attached}},1}},#[fg={theme["info"]}]{glyphs["clients"]} #{{session_attached}}#[fg={theme["sep"]}]{glyphs["sep"]},}}'

    clock_part = ""
    if segments.get("clock", True):
        clock_part = f'#[fg={theme["fg"]},bold]{clock_fmt} '

    status_right = f'#({status_right_script}){multi_client_part}{clock_part}'

    # Window status tabs
    win_mode = windows_cfg.get("mode", "hidden")
    if win_mode == "hidden":
        window_format_lines = [
            'set -g window-status-format ""',
            'set -g window-status-current-format ""',
            'set -g window-status-separator ""',
        ]
    elif win_mode == "minimal":
        window_format_lines = [
            f'set -g window-status-format "#[fg={theme["dim"]}] #I:#W "',
            f'set -g window-status-current-format "#[fg={theme["accent"]},bold] #I:#W "',
            f'set -g window-status-separator "#[fg={theme["sep"]}]|"',
        ]
    else:  # "tabs"
        window_format_lines = [
            f'set -g window-status-format "#[fg={theme["dim"]},bg={theme["border"]}] #I #[fg={theme["fg"]},bg={theme["message_bg"]}] #W "',
            f'set -g window-status-current-format "#[fg={theme["bg"]},bg={theme["accent"]},bold] #I #[fg={theme["fg"]},bg={theme["mode_bg"]}] #W "',
            'set -g window-status-separator " "',
        ]

    lines = [
        f"# tmux-sentinel configuration - Theme: {theme['name']}",
        "# Generated automatically by tmux-sentinel. Do not edit directly.",
        "",
        "set -g status on",
        f"set -g status-position {pos}",
        f"set -g status-interval {interval}",
        "set -g status-justify left",
        f'set -g status-style "bg={theme["bg"]},fg={theme["fg"]}"',
        "",
        "# Window list display mode",
        *window_format_lines,
        "",
        "# Status Left: Accent mode indicator + session identity",
        "set -g status-left-length 30",
        f'set -g status-left "{status_left}"',
        "",
        "# Status Right: Host health & alert segments",
        "set -g status-right-length 100",
        f'set -g status-right "{status_right}"',
        "",
        "# Window & Pane Chrome",
        f'set -g message-style "bg={theme["message_bg"]},fg={theme["fg"]}"',
        f'set -g message-command-style "bg={theme["message_bg"]},fg={theme["warn"]}"',
        f'set -g mode-style "bg={theme["mode_bg"]},fg={theme["fg"]}"',
        f'set -g pane-border-style "fg={theme["border"]}"',
        f'set -g pane-active-border-style "fg={theme["active_border"]}"',
        "",
    ]

    with open(TMUX_CONF_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
