# tmux-sentinel theme: Catppuccin Macchiato
# Description: Medium-contrast dark Catppuccin variant

set -g status-style "bg=default,fg=#cad3f5"

# Mode & Prefix indicator
set -g status-left "#[fg=#{?client_prefix,#ed8796,#{?pane_in_mode,#eed49f,#8aadf4}}]▌#[fg=#cad3f5,bold] #{=/18/…:session_name} #[default]"

# Chrome
set -g message-style "bg=#363a4f,fg=#cad3f5"
set -g message-command-style "bg=#363a4f,fg=#eed49f"
set -g mode-style "bg=#494d64,fg=#cad3f5"
set -g pane-border-style "fg=#363a4f"
set -g pane-active-border-style "fg=#8aadf4"
