# tmux-sentinel theme: Monokai Pro
# Description: Modernized high-contrast spectrum on charcoal

set -g status-style "bg=default,fg=#fcfcfa"

# Mode & Prefix indicator
set -g status-left "#[fg=#{?client_prefix,#ff6188,#{?pane_in_mode,#ffd866,#78dce8}}]▌#[fg=#fcfcfa,bold] #{=/18/…:session_name} #[default]"

# Chrome
set -g message-style "bg=#221f22,fg=#fcfcfa"
set -g message-command-style "bg=#221f22,fg=#ffd866"
set -g mode-style "bg=#403e41,fg=#fcfcfa"
set -g pane-border-style "fg=#2d2a2e"
set -g pane-active-border-style "fg=#78dce8"
