# tmux-sentinel theme: Nord
# Description: Arctic, north-bluish clean aesthetic

set -g status-style "bg=default,fg=#d8dee9"

# Mode & Prefix indicator
set -g status-left "#[fg=#{?client_prefix,#bf616a,#{?pane_in_mode,#ebcb8b,#88c0d0}}]▌#[fg=#d8dee9,bold] #{=/18/…:session_name} #[default]"

# Chrome
set -g message-style "bg=#2e3440,fg=#d8dee9"
set -g message-command-style "bg=#2e3440,fg=#ebcb8b"
set -g mode-style "bg=#434c5e,fg=#d8dee9"
set -g pane-border-style "fg=#3b4252"
set -g pane-active-border-style "fg=#88c0d0"
