# tmux-sentinel theme: One Dark
# Description: Atom and VS Code iconic balanced dark theme

set -g status-style "bg=default,fg=#abb2bf"

# Mode & Prefix indicator
set -g status-left "#[fg=#{?client_prefix,#e06c75,#{?pane_in_mode,#d19a66,#61afef}}]▌#[fg=#abb2bf,bold] #{=/18/…:session_name} #[default]"

# Chrome
set -g message-style "bg=#21252b,fg=#abb2bf"
set -g message-command-style "bg=#21252b,fg=#e5c07b"
set -g mode-style "bg=#3e4451,fg=#abb2bf"
set -g pane-border-style "fg=#282c34"
set -g pane-active-border-style "fg=#61afef"
