# tmux-sentinel theme: Rosé Pine
# Description: All natural pine, faux fur, and dusky floral rose

set -g status-style "bg=default,fg=#e0def4"

# Mode & Prefix indicator
set -g status-left "#[fg=#{?client_prefix,#eb6f92,#{?pane_in_mode,#f6c177,#9ccfd8}}]▌#[fg=#e0def4,bold] #{=/18/…:session_name} #[default]"

# Chrome
set -g message-style "bg=#21202e,fg=#e0def4"
set -g message-command-style "bg=#21202e,fg=#f6c177"
set -g mode-style "bg=#393552,fg=#e0def4"
set -g pane-border-style "fg=#26233a"
set -g pane-active-border-style "fg=#9ccfd8"
